apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-granted-to-target
spec:
  podSelector:
    matchLabels:
      app: target-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: granted
      ports:
        - protocol: TCP
          port: 80
